# Generated by Django 6.0.2 on 2026-02-18 18:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('MC', 'Mujer Creativa y Cultural'), ('ME', 'Mujer Emprendedora y Líder'), ('MI', 'Mujer Innovadora')], max_length=2, unique=True, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Emprendedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('nombre_emprendimiento', models.CharField(max_length=255, verbose_name='Nombre del Emprendimiento')),
                ('departamento', models.CharField(choices=[('BO', 'Boaco'), ('CA', 'Carazo'), ('CI', 'Chinandega'), ('CO', 'Chontales'), ('ES', 'Estelí'), ('GR', 'Granada'), ('JI', 'Jinotega'), ('LE', 'León'), ('MD', 'Madriz'), ('MN', 'Managua'), ('MS', 'Masaya'), ('MA', 'Matagalpa'), ('NS', 'Nueva Segovia'), ('RI', 'Rivas'), ('RS', 'Río San Juan'), ('AN', 'RACCN'), ('AS', 'RACCS')], max_length=2, verbose_name='Departamento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('carta_interes', models.TextField(verbose_name='Carta de Interés')),
                ('anios_funcionamiento', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2, message='Debe tener al menos 2 años de funcionamiento.')], verbose_name='Años de Funcionamiento')),
                ('empleos_generados', models.CharField(help_text='Ej: Directos: 3, Indirectos: 5', max_length=100, verbose_name='Empleos Generados')),
                ('descripcion_negocio', models.TextField(verbose_name='Descripción del Negocio')),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del Producto/Servicio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Emprendedora',
                'verbose_name_plural': 'Emprendedoras',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('score_coherencia', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='1. Coherencia con la Categoría')),
                ('score_trayectoria', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='2. Trayectoria y Liderazgo')),
                ('score_impacto', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='3. Impacto en el Entorno/Empleo')),
                ('score_creatividad', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='4. Nivel de Innovación/Creatividad')),
                ('score_viabilidad', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='5. Proyección y Estabilidad')),
                ('score_inversion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='6. Intención de Uso del Premio')),
                ('score_presentacion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='7. Claridad en Carta/Pitch')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('total_score', models.PositiveIntegerField(default=0, editable=False, verbose_name='Puntaje Total')),
                ('emprendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='evaluacion.emprendedora')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'unique_together': {('jurado', 'emprendedora')},
            },
        ),
    ]
