# Generated by Django 6.0.2 on 2026-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedora',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección del Domicilio'),
        ),
        migrations.AddField(
            model_name='emprendedora',
            name='email',
            field=models.EmailField(default=1, help_text='Este campo se usa como identificador único.', max_length=254, unique=True, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendedora',
            name='numero_cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Cédula'),
        ),
        migrations.AddField(
            model_name='emprendedora',
            name='requiere_revision',
            field=models.BooleanField(default=False, verbose_name='Requiere Revisión'),
        ),
        migrations.AddField(
            model_name='emprendedora',
            name='revision_motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo de Revisión'),
        ),
        migrations.AddField(
            model_name='emprendedora',
            name='url_foto_cedula',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL Foto de Cédula'),
        ),
    ]
