# Generated by Django 6.0.2 on 2026-02-18 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_emprendedora_direccion_emprendedora_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendedora',
            name='foto_producto',
        ),
        migrations.AddField(
            model_name='emprendedora',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_galeria/', verbose_name='Imagen del Producto')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción Corta')),
                ('emprendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_productos', to='evaluacion.emprendedora')),
            ],
            options={
                'verbose_name': 'Foto de Producto',
                'verbose_name_plural': 'Galería de Productos',
            },
        ),
    ]
