# Generated by Django 6.0.2 on 2026-03-01 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_remove_emprendedora_foto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='score_fase1',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Puntaje Fase 1 (60%)'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='score_pitch',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='8. Calificación Pitch Final (0-100)'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Puntaje Final Ponderado'),
        ),
    ]
